version: '3.8'
services:

  restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    command:
      - /opt/docspell.conf
    restart: unless-stopped
    ports:
      - "7880:7880"
    volumes:
      - ./docspell.conf:/opt/docspell.conf
